---

sudo: required
services:
  - docker

# Build test image for the React Project
before_install:
  - docker build -t nabeelhamadal/react-test -f ./client/Dockerfile.dev ./client

# Run the test (exit 0 = success, exist not 0 = none success)
script:
  - docker run -e CI=true nabeelhamadal/react-test npm test

# If success, Build production version of all projects
after_success:
  - docker build -t nabeelhamadal/multi-client ./client
  - docker build -t nabeelhamadal/multi-api ./api
  - docker build -t nabeelhamadal/multi-nginx ./nginx
  - docker build -t nabeelhamadal/multi-worker ./worker

  # Login Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images above to Docker Hub
  - docker push nabeelhamadal/multi-client
  - docker push nabeelhamadal/multi-api
  - docker push nabeelhamadal/multi-nginx
  - docker push nabeelhamadal/multi-worker


# Deploy from Travis to Elastic Beans
deploy:
  provider: elasticbeanstalk
  region: 'eu-west-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-500139711733'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY