version: '3'
services:

  # Create the poxy image / nginx
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80   # (host-port:container-port)
    depends_on:
      - api
      - client


  # Stores all the previously run calculations
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres_password

  # Redis is in-memory database meaning it will store the current run calculation before
  # presenting it to the user
  redis:
    image: redis:latest


  # This is the container which manages the calculation process
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432


  # This is the container which provides you with the React front page website
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app


  # This is where the Fibonacci calculation is run
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


